# 用户名（可以是手机号，也可以是12306设置的用户名）
username : '12345678901'
# 密码
password : 'a123456'
# 身份证号后四位
id_card : '1145'
# 车票未开售时刷新秒数，建议设置在120-150之间，太短会导致查询超时，太长会导致登录信息失效
heart : 120
# 若乘客为学生身份，是否购买学生票(y/n)
isStu : n