// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ysaygdcpwfqkwysprwxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlzYXlnZGNwd2Zxa3d5c3Byd3h6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUwMDYwMzYsImV4cCI6MjA1MDU4MjAzNn0.JAZ3EILpvZ_eMkDoI2cjxex41ujykFgmHZGH1YhAbO0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);